In [4]:
# import pandas as pd
# import json
# import numpy
# import os
# from pathlib import Path
# from datetime import date, timedelta
# import urllib.parse
# import time
# import requests

# # https://docs.slack.dev/tools/python-slack-sdk
# from slack_sdk.webhook import WebhookClient
# from slack_sdk.errors import SlackApiError


# # the URL we'll send slack alerts to
# SLACK_WEBHOOK = "https://hooks.slack.com/services/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"

# # the slack API only allows sending 50 block elements at a time
# MAX_SLACK_BLOCKS = 50

# def send_message(content, webhook):  # send message to webhook
#     message = {"text": content}
#     message_json = json.dumps(message)
#     return requests.post(webhook, message_json)

# send_message("Hello!",SLACK_WEBHOOK)

In [3]:
import pandas as pd
import json
import numpy
import os
from pathlib import Path
from datetime import date, timedelta
import urllib.parse
import time
import requests

# https://docs.slack.dev/tools/python-slack-sdk
from slack_sdk.webhook import WebhookClient
from slack_sdk.errors import SlackApiError


# the URL we'll send slack alerts to
SLACK_WEBHOOK = SLACK_WEBHOOK_HEATBOT

# the slack API only allows sending 50 block elements at a time
MAX_SLACK_BLOCKS = 50

def send_message(content, webhook):  # send message to webhook
    message = {"text": content}
    message_json = json.dumps(message)
    return requests.post(webhook, message_json)

send_message("slayyyyy!",SLACK_WEBHOOK)

In [8]:
test_df = pd.read_csv('./data/test/all_mod1.csv')
test_df2 = pd.read_csv('./data/test/all_mod2.csv')

In [9]:
def splitdate(df):
    df[['inc_date','inc_time']] = df['incident_date'].str.split('T', expand=True)
    df[['dth_date', 'dth_time']] = df['death_date'].str.split('T', expand=True)

splitdate(test_df)
test_df

,Unnamed: 0,casenumber,incident_date,death_date,age,gender,race,latino,manner,primarycause,...,chi_commarea,covid_related,:id,:created_at,:updated_at,primarycause_lineb,inc_date,inc_time,dth_date,dth_time
0,0,ME2016-03171,2016-06-27T15:24:00.000,2016-06-27T16:36:00.000,83,Female,Black,False,NATURAL,HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...,...,ROSELAND,False,row-cjgt_crd7-xyuy,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2016-06-27,15:24:00.000,2016-06-27,16:36:00.000
1,1,ME2017-04963,2017-10-22T04:56:00.000,2017-10-22T05:55:00.000,61,Male,Black,False,ACCIDENT,HYPERTHERMIA. EXPOSURE TO HIGH ENVIRONMENTAL T...,...,NaN,False,row-anqg-rrnp-nc7f,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,EXPOSURE TO HIGH ENVIRONMENTAL TEMPERATURE,2017-10-22,04:56:00.000,2017-10-22,05:55:00.000
2,2,ME2017-04962,2017-10-22T08:50:00.000,2017-10-22T09:28:00.000,44,Male,Black,False,ACCIDENT,HYPERTHERMIA . EXPOSURE TO HIGH ENVIRONMENTAL ...,...,NaN,False,row-zkkj-326b.5nki,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,EXPOSURE TO HIGH ENVIRONMENTAL TEMPERATURE,2017-10-22,08:50:00.000,2017-10-22,09:28:00.000
3,3,ME2019-02763,2019-06-17T15:00:00.000,2019-06-17T15:55:00.000,76,Male,Black,False,ACCIDENT,ENVIRONMENTAL HEAT EXPOSURE. FAULTY MODIFICATI...,...,NaN,False,row-bdwb~ncpq_653d,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,FAULTY MODIFICATION OF HOME FURNACE AND THERMO...,2019-06-17,15:00:00.000,2019-06-17,15:55:00.000
4,4,ME2015-03061,2015-07-19T01:00:00.000,2015-07-19T01:40:00.000,70,Female,White,False,NATURAL,HYPERTENSIVE CARDIOVASCULAR DISEASE,...,NaN,False,row-u2wg.si6s.22un,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2015-07-19,01:00:00.000,2015-07-19,01:40:00.000
5,5,ME2018-03047,2018-06-30T09:33:00.000,2018-06-30T09:45:00.000,49,Male,White,False,NATURAL,HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...,...,WEST TOWN,False,row-4s8n~kc2j-xr4s,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2018-06-30,09:33:00.000,2018-06-30,09:45:00.000
6,6,ME2018-03654,2018-08-04T12:45:00.000,2018-08-04T13:23:00.000,81,Female,Black,False,NATURAL,HYPERTENSIVE CARDIOVASCULAR DISEASE,...,NORTH LAWNDALE,False,row-qnfn_9dzi.ryh2,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2018-08-04,12:45:00.000,2018-08-04,13:23:00.000
7,7,ME2016-03895,2016-08-10T11:26:00.000,2016-08-10T18:13:00.000,47,Female,White,True,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,...,PULLMAN,False,row-89ey~272e.kmpt,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2016-08-10,11:26:00.000,2016-08-10,18:13:00.000
8,8,ME2015-03222,2015-07-28T19:37:00.000,2015-07-28T20:39:00.000,73,Female,White,False,NATURAL,ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE,...,ALBANY PARK,False,row-cv5x_vpkg_t5y2,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2015-07-28,19:37:00.000,2015-07-28,20:39:00.000
9,9,ME2015-01578,2015-04-17T19:45:00.000,2015-04-17T20:51:00.000,90,Female,Black,False,ACCIDENT,HYPERTENSIVE CARDIOVASCULAR DISEASE,...,WASHINGTON HEIGHTS,False,row-69nx_tzpf~gwgh,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2015-04-17,19:45:00.000,2015-04-17,20:51:00.000
10,10,ME2015-03060,2015-07-19T01:40:00.000,2015-07-19T02:02:00.000,69,Female,Black,False,NATURAL,HYPERTENSIVE CARDIOVASCULAR DISEASE,...,AUSTIN,False,row-rpfe.upfy-6i43,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2015-07-19,01:40:00.000,2015-07-19,02:02:00.000
11,11,ME2016-03517,2016-07-19T14:06:00.000,2016-07-19T14:46:00.000,63,Male,Black,False,NATURAL,HYPERTENSIVE AND ATHEROSCLEROTIC CARDIOVASCULA...,...,AUSTIN,False,row-abf4~55am.fuim,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2016-07-19,14:06:00.000,2016-07-19,14:46:00.000
12,12,ME2018-02328,2018-05-16T17:25:00.000,2018-05-16T18:10:00.000,61,Female,Black,False,ACCIDENT,ENVIRONMENTAL HEAT EXPOSURE . MALFUNCTION OF A...,...,ASHBURN,False,row-aabb~uneg-iqw7,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,MALFUNCTION OF A RESIDENTIAL THERMOSTAT,2018-05-16,17:25:00.000,2018-05-16,18:10:00.000
13,13,ME2018-03034,2018-06-29T16:10:00.000,2018-06-29T16:20:00.000,36,Female,White,False,ACCIDENT,ETHANOL AND AMPHETAMINE TOXICITY,...,LINCOLN PARK,False,row-a6w7~azdj_7tzw,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2018-06-29,16:10:00.000,2018-06-29,16:20:00.000
14,14,ME2019-03094,2019-07-05T10:30:00.000,2019-07-05T11:00:00.000,87,Female,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,...,LOGAN SQUARE,False,row-2dcz.ifbk-2qam,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2019-07-05,10:30:00.000,2019-07-05,11:00:00.000
15,15,ME2019-03360,2019-07-20T14:49:00.000,2019-07-20T15:41:00.000,54,Male,White,False,NATURAL,CORONARY ATHEROSCLEROSIS,...,LINCOLN SQUARE,False,row-dr7b-ndbe~kyum,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2019-07-20,14:49:00.000,2019-07-20,15:41:00.000
16,16,ME2019-03279,2019-05-05T11:30:00.000,2019-07-15T11:24:00.000,66,Male,White,False,ACCIDENT,HYPERTENSIVE AND ATHEROSCLEROTIC CARDIOVASCULA...,...,LAKE VIEW,False,row-6efr-yfxa-pdtz,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2019-05-05,11:30:00.000,2019-07-15,11:24:00.000
17,17,ME2019-03366,2019-07-20T21:25:00.000,2019-07-20T21:50:00.000,71,Female,Black,False,NATURAL,HYPERTENSIVE-ARTERIOSCLEROTIC CARDIOVASCULAR D...,...,EAST GARFIELD PARK,False,row-rbn4_2svs-xuwe,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2019-07-20,21:25:00.000,2019-07-20,21:50:00.000
18,18,ME2019-03372,2019-07-19T16:55:00.000,2019-07-21T06:23:00.000,56,Male,White,False,ACCIDENT,COMPLICATIONS OF HYPERTHERMIA. HEAT STROKE,...,LOGAN SQUARE,False,row-38rh~sugb_i5qr,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,HEAT STROKE,2019-07-19,16:55:00.000,2019-07-21,06:23:00.000
19,19,ME2019-05081,2019-10-28T11:02:00.000,2019-10-28T11:45:00.000,61,Female,Black,False,NATURAL,HYPERTENSIVE AND ATHEROSCLEROTIC CARDIOVASCULA...,...,CHATHAM,False,row-e459.j7py_pccy,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2019-10-28,11:02:00.000,2019-10-28,11:45:00.000
20,20,ME2019-05731,2019-12-03T09:00:00.000,2019-12-03T09:49:00.000,79,Female,Black,False,ACCIDENT,ENVIRONMENTAL HEAT EXPOSURE. MALFUNCTION OF RE...,...,ASHBURN,False,row-2ftk_xts3~5sgs,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,MALFUNCTION OF RESIDENTIAL HEATING SYSTEM,2019-12-03,09:00:00.000,2019-12-03,09:49:00.000
21,21,ME2020-01244,2020-03-06T20:50:00.000,2020-03-06T21:33:00.000,55,Male,White,False,NATURAL,ATHEROSCLEROTIC CORONARY ARTERY DISEASE.,...,LAKE VIEW,False,row-aqg3.ijzh.7jwp,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2020-03-06,20:50:00.000,2020-03-06,21:33:00.000
22,22,ME2020-08242,2020-06-25T14:51:00.000,2020-06-27T00:59:00.000,40,Male,White,True,ACCIDENT,COMPLICATIONS OF HYPERTHERMIA. COMBINATION OF ...,...,HUMBOLDT PARK,False,row-q6a4.pcf7.xazw,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,COMBINATION OF ENVIRONMENT AND FENTANYL AND CA...,2020-06-25,14:51:00.000,2020-06-27,00:59:00.000
23,23,ME2020-08357,2020-06-27T20:56:00.000,2020-06-27T22:04:00.000,54,Female,White,False,ACCIDENT,HEAT STROKE,...,NaN,False,row-u5ws.w6f2.qc62,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2020-06-27,20:56:00.000,2020-06-27,22:04:00.000
24,24,ME2020-08539,2020-07-01T16:57:00.000,2020-07-02T15:25:00.000,95,Female,Asian,False,ACCIDENT,HYPERTHERMIA. HEAT EXPOSURE,...,MONTCLARE,False,row-scpq.6bea-dukr,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,HEAT EXPOSURE,2020-07-01,16:57:00.000,2020-07-02,15:25:00.000
25,25,ME2020-08771,2020-07-09T12:30:00.000,2020-07-09T13:00:00.000,18,Female,White,True,ACCIDENT,HEAT STROKE,...,NaN,False,row-arry-74j3.gxt2,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2020-07-09,12:30:00.000,2020-07-09,13:00:00.000
26,26,ME2020-11109,2020-10-04T14:10:00.000,2020-10-04T14:27:00.000,80,Male,Black,False,ACCIDENT,ENVIRONMENTAL HEAT EXPOSURE. FURNACE MALFUNCTI...,...,NaN,False,row-w66d-t2az_pjtj,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,FURNACE MALFUNCTIONING,2020-10-04,14:10:00.000,2020-10-04,14:27:00.000
27,27,ME2020-11117,2020-10-04T14:10:00.000,2020-10-04T18:49:00.000,78,Female,Black,False,ACCIDENT,HYPERTHERMIA. FURNACE MALFUNCTIONING,...,NaN,False,row-zqq5.hk2v~z3xq,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,FURNACE MALFUNCTIONING,2020-10-04,14:10:00.000,2020-10-04,18:49:00.000
28,28,ME2021-06815,2021-07-04T00:00:00.000,2021-07-17T06:34:00.000,65,Female,Black,False,ACCIDENT,COMPLICATIONS OF HEAT STROKE,...,DOUGLAS,False,row-b8ms~7syy~iujg,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2021-07-04,00:00:00.000,2021-07-17,06:34:00.000
29,29,ME2021-07018,2021-07-24T17:16:00.000,2021-07-24T22:18:00.000,54,Male,White,False,ACCIDENT,FENTANYL AND PROBABLE COCAINE TOXICITY,...,WEST TOWN,False,row-gbc9~2a3j~yy5u,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2021-07-24,17:16:00.000,2021-07-24,22:18:00.000
30,30,ME2022-05305,2022-05-14T14:00:00.000,2022-05-14T14:39:00.000,76,Female,Black,False,ACCIDENT,ENVIRONMENTAL HEAT EXPOSURE. HOT RESIDENTIAL B...,...,ROGERS PARK,False,row-mbkp-2h3w~2zy7,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,HOT RESIDENTIAL BUILDING DURING HEAT-RELATED W...,2022-05-14,14:00:00.000,2022-05-14,14:39:00.000
31,31,ME2022-05310,2022-05-14T19:00:00.000,2022-05-14T19:04:00.000,72,Female,Black,False,ACCIDENT,ENVIRONMENTAL HEAT EXPOSURE. HOT RESIDENTIAL B...,...,ROGERS PARK,False,row-h4xy_wi5x.iby5,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,HOT RESIDENTIAL BUILDING DURING HEAT-RELATED W...,2022-05-14,19:00:00.000,2022-05-14,19:04:00.000
32,32,ME2022-05306,2022-05-14T11:10:00.000,2022-05-14T11:32:00.000,68,Female,Black,False,ACCIDENT,ENVIRONMENTAL HEAT EXPOSURE . HOT RESIDENTIAL ...,...,ROGERS PARK,False,row-xj7q-kgue.dscz,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,HOT RESIDENTIAL BUILDING DURING A HEAT-RELATED...,2022-05-14,11:10:00.000,2022-05-14,11:32:00.000
33,33,ME2022-05975,2022-06-14T18:33:00.000,2022-06-14T19:18:00.000,66,Female,Black,False,ACCIDENT,HYPERTHERMIA. ENVIRONMENTAL HEAT EXPOSURE,...,NEAR SOUTH SIDE,False,row-yxda_7uj4~5rhc,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,ENVIRONMENTAL HEAT EXPOSURE,2022-06-14,18:33:00.000,2022-06-14,19:18:00.000
34,34,ME2022-06215,2022-06-15T00:00:00.000,2022-06-25T21:16:00.000,77,Female,White,False,NATURAL,CORONARY ARTERY DISEASE,...,NaN,False,row-79cm_2ksd-b9p8,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2022-06-15,00:00:00.000,2022-06-25,21:16:00.000
35,35,ME2022-07256,2022-08-11T08:15:00.000,2022-08-11T08:30:00.000,31,Male,White,False,ACCIDENT,CHRONIC ETHANOLISM,...,AVONDALE,False,row-ujup-mp7e-tbj4,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2022-08-11,08:15:00.000,2022-08-11,08:30:00.000
36,36,ME2022-09517,2022-11-24T09:45:00.000,2022-11-24T09:55:00.000,58,Female,Black,False,ACCIDENT,ENVIRONMENTAL HEAT EXPOSURE. HOT APARTMENT UNI...,...,WEST ENGLEWOOD,False,row-2km4_wjfk~u6m5,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,HOT APARTMENT UNIT IN RESIDENTIAL BUILDING,2022-11-24,09:45:00.000,2022-11-24,09:55:00.000
37,37,ME2023-03049,2023-05-20T19:12:00.000,2023-05-20T10:41:00.000,60,Female,White,False,ACCIDENT,HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...,...,WOODLAWN,False,row-rvat_dsh4_48ia,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2023-05-20,19:12:00.000,2023-05-20,10:41:00.000
38,38,ME2023-03958,2023-06-30T15:05:00.000,2023-06-30T13:38:00.000,53,Male,White,False,NATURAL,ATHEROSCLEROTIC CARDIOVASCULAR DISEASE,...,NaN,False,row-fy3a_8yc9~xm8f,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2023-06-30,15:05:00.000,2023-06-30,13:38:00.000
39,39,ME2023-04799,2023-08-11T11:15:00.000,2023-08-11T10:54:00.000,33,Male,Black,False,ACCIDENT,"COMBINED DRUG (COCAINE, FENTANYL, AND 4-ANPP (...",...,WEST ENGLEWOOD,False,row-fuen.gn2q.thep,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2023-08-11,11:15:00.000,2023-08-11,10:54:00.000
40,40,ME2024-02421,2024-04-30T12:18:00.000,2024-04-30T11:30:00.000,68,Male,Black,False,ACCIDENT,COMPLICATIONS OF HEAT STROKE,...,NaN,False,row-vsbi.8xr4.v98v,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2024-04-30,12:18:00.000,2024-04-30,11:30:00.000
41,41,ME2024-03289,2024-06-18T12:23:00.000,2024-06-18T10:29:00.000,83,Female,Black,False,NATURAL,HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...,...,AUBURN GRESHAM,False,row-kktx~vqbs_jehn,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2024-06-18,12:23:00.000,2024-06-18,10:29:00.000
42,42,ME2024-04024,2024-07-23T16:33:00.000,2024-07-23T16:22:00.000,62,Male,Black,False,ACCIDENT,FENTANYL AND DIPHENHYDRAMINE TOXICITY,...,NaN,False,row-qad3~nzzr-qcup,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2024-07-23,16:33:00.000,2024-07-23,16:22:00.000
43,43,ME2024-04714,2024-08-27T00:43:00.000,2024-08-28T00:27:00.000,35,Male,Black,False,NATURAL,HYPERTROPHIC CARDIOMYOPATHY,...,AUSTIN,False,row-3tdg-vit8.j6e2,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2024-08-27,00:43:00.000,2024-08-28,00:27:00.000
44,44,ME2024-07003,2024-12-21T15:26:00.000,2024-12-21T13:35:00.000,60,Female,White,False,ACCIDENT,ENVIRONMENTAL HEAT EXPOSURE . PROLONGED CONTAC...,...,NaN,False,row-uy6e.kxrx_uv5v,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,PROLONGED CONTACT WITH HOT SHOWER WATER,2024-12-21,15:26:00.000,2024-12-21,13:35:00.000
45,45,ME2025-02669,2025-05-15T19:55:00.000,2025-05-15T17:46:00.000,80,Female,Am. Indian,False,ACCIDENT,HEAT STROKE,...,NaN,False,row-qgn6-88u2-djxv,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2025-05-15,19:55:00.000,2025-05-15,17:46:00.000
46,46,ME2025-03384,2025-06-24T18:50:00.000,2025-06-24T16:25:00.000,40,Male,White,True,ACCIDENT,ACUTE ETHANOL TOXICITY,...,GAGE PARK,False,row-9tkf_2seb~gppz,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2025-06-24,18:50:00.000,2025-06-24,16:25:00.000
47,47,ME2025-03437,2025-06-26T15:30:00.000,2025-06-26T14:37:00.000,82,Male,White,False,NATURAL,HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...,...,NORWOOD PARK,False,row-vgr8~txzr.i4h8,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2025-06-26,15:30:00.000,2025-06-26,14:37:00.000
48,48,ME2025-03680,2025-07-07T18:53:00.000,2025-07-07T18:02:00.000,70,Male,White,True,NATURAL,MYOCARDIAL INFARCTION. HYPERTENSIVE-ARTERIOSCL...,...,OHARE,False,row-tqk4-dc8y.z2g6,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,HYPERTENSIVE-ARTERIOSCLEROTIC-VALVULAR HEART D...,2025-07-07,18:53:00.000,2025-07-07,18:02:00.000
49,49,ME2026-03456,2026-07-01T13:09:00.000,2026-07-01T12:32:00.000,69,Male,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,...,NaN,False,row-qr98-f75u.wfvp,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2026-07-01,13:09:00.000,2026-07-01,12:32:00.000
50,50,ME2026-03475,2026-07-01T23:33:00.000,2026-07-01T20:31:00.000,46,Male,White,False,ACCIDENT,HYPERTHERMIA. ENVIRONMENTAL HEAT EXPOSURE IN T...,...,CHICAGO LAWN,False,row-rzej~pb48-7b4c,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,ENVIRONMENTAL HEAT EXPOSURE IN THE SETTING OF ...,2026-07-01,23:33:00.000,2026-07-01,20:31:00.000

In [7]:
display(test_df)

None

In [65]:
test_df[['inc_date', 'inc_time']] = test_df['incident_date'].str.split('T', expand=True)
test_df[['inc_date', 'inc_time']] = test_df['incident_date'].str.split('T', expand=True)
test_df[['dth_date', 'dth_time']] = test_df['death_date'].str.split('T', expand=True)
test_df[['dth_date', 'dth_time']] = test_df['death_date'].str.split('T', expand=True)

test_df2[['inc_date', 'inc_time']] = test_df2['incident_date'].str.split('T', expand=True)
test_df2[['inc_date', 'inc_time']] = test_df2['incident_date'].str.split('T', expand=True)
test_df2[['dth_date', 'dth_time']] = test_df2['death_date'].str.split('T', expand=True)
test_df2[['dth_date', 'dth_time']] = test_df2['death_date'].str.split('T', expand=True)

In [33]:
agency = "datacatalog.cookcountyil.gov"
dataset = "cjeq-bs86" # this is the shortlink!
stringlink = f'https://{agency}/d/{dataset}'
gitlink = "https://github.com/cam-rodriguez/cpm_heatbot/tree/a207489e7adb54302c4755b1a0c7349fbddd6413/data"

In [ ]:
# slack link formatting
# <https://docs.slack.dev/|This message is a link>

In [101]:
def textgenerator(df1, df2):
    length = len(df2) - len(df1)

    if length == 0:
        txt = f"*No new data* was added to the dataset between the last scrape and this one. \n <{stringlink}|Click here> to view the data portal, and <{gitlink}|here> to view the most recent copy."

    elif length == 1:
        txt = f"*One new row* was added to the dataset between the last scrape and this one. \n <{stringlink}|Click here> to view the data portal, and <{gitlink}|here> to view the most recent copy. <!channel>"

    elif length > 1:
        txt = f"*{length} new rows* were added to the dataset between the last scrape and this one. \n <{stringlink}|Click here> to view the data portal, and <{gitlink}|here> to view the most recent copy. <!channel>"

    else:
        txt = f"Error of some kind..."
    
    return txt

In [18]:
newrows = test_df2[~test_df2.isin(test_df)] # where rows in the new dataframe aren't in the older dataframe
newrows = newrows[~newrows['casenumber'].isna()] # where case number is not null...
# newrows = newrows.dropna()
newrows # print new rows

,Unnamed: 0,casenumber,incident_date,death_date,age,gender,race,latino,manner,primarycause,...,residence_city,residence_zip,objectid,chi_ward,chi_commarea,covid_related,:id,:created_at,:updated_at,primarycause_lineb
51,51.0,ME2026-03491,2026-07-02T15:57:00.000,2026-07-02T15:32:00.000,48.0,Male,Black,False,ACCIDENT,HEAT STROKE,...,Chicago,60612.0,97283.0,28.0,EAST GARFIELD PARK,False,row-4agc.n45x.zqvw,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN
52,52.0,ME2026-03506,2026-07-03T10:18:00.000,2026-07-03T10:01:00.000,57.0,Male,White,True,NATURAL,HYPERTENSIVE AND ATHEROSCLEROTIC CARDIOVASCULA...,...,Chicago,60608.0,97297.0,12.0,MCKINLEY PARK,False,row-8b9p.nu4n~5fcf,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN
53,53.0,ME2026-03513,2026-07-03T17:48:00.000,2026-07-03T17:25:00.000,71.0,Female,Black,False,NATURAL,HYPERTENSIVE CARDIOVASCULAR DISEASE,...,Chicago,60621.0,97304.0,16.0,ENGLEWOOD,False,row-mt4y_zt3v_skr2,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN
54,54.0,ME2026-03523,2026-07-02T12:50:00.000,2026-07-04T12:15:00.000,44.0,Male,White,True,ACCIDENT,HEAT STROKE,...,Chicago,60629.0,97311.0,15.0,CHICAGO LAWN,False,row-j46t-672f_76u9,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN
55,55.0,ME2026-03638,2026-06-29T00:00:00.000,2026-07-09T15:52:00.000,45.0,Female,White,True,ACCIDENT,COMPLICATIONS OF HEAT STROKE,...,Chicago,60619.0,97432.0,20.0,NEW CITY,False,row-y2ii_8nfn-x5yk,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN
56,56.0,ME2026-03649,2026-06-29T10:00:00.000,2026-07-10T02:07:00.000,77.0,Male,White,False,ACCIDENT,COMPLICATIONS OF FALL(S),...,Westchester,60154.0,97441.0,NaN,NaN,False,row-jfra-wevt~r7nj,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN
57,57.0,ME2026-03743,2026-07-14T11:27:00.000,2026-07-14T10:51:00.000,65.0,Male,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,...,Oak Lawn,60453.0,97541.0,NaN,NaN,False,row-r52t~k593-98rx,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN

In [19]:
newrows['casenumber']

51    ME2026-03491
52    ME2026-03506
53    ME2026-03513
54    ME2026-03523
55    ME2026-03638
56    ME2026-03649
57    ME2026-03743
Name: casenumber, dtype: str

In [ ]:
test_df.head(2)

,Unnamed: 0,casenumber,incident_date,death_date,age,gender,race,latino,manner,primarycause,...,residence_city,residence_zip,objectid,chi_ward,chi_commarea,covid_related,:id,:created_at,:updated_at,primarycause_lineb
0,0,ME2016-03171,2016-06-27T15:24:00.000,2016-06-27T16:36:00.000,83,Female,Black,False,NATURAL,HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...,...,Chicago,60629,2739,9.0,ROSELAND,False,row-cjgt_crd7-xyuy,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN
1,1,ME2017-04963,2017-10-22T04:56:00.000,2017-10-22T05:55:00.000,61,Male,Black,False,ACCIDENT,HYPERTHERMIA. EXPOSURE TO HIGH ENVIRONMENTAL T...,...,Richton Park,60471,4762,NaN,NaN,False,row-anqg-rrnp-nc7f,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,EXPOSURE TO HIGH ENVIRONMENTAL TEMPERATURE

In [31]:
textgenerator(test_df, test_df2)

'*7 new rows* were added to the dataset between the last scrape and this one.'

In [28]:
send_message("slayyyyy!",SLACK_WEBHOOK) # send message to heatbot channel/webhook of choice

In [91]:
from datetime import datetime, timedelta
rightnow = datetime.now().strftime('%A %B %d %I:%M %p')

In [92]:
print(rightnow)

Tuesday August 04 03:37 PM

In [97]:
placeholder = "Heat deaths"

In [102]:
text = textgenerator(test_df, test_df2)
formatted = f'❗️ *{placeholder} update, {rightnow}* \n {text}'
send_message(formatted, SLACK_WEBHOOK)

In [ ]:
def diffgenerator(test_df, test_df2):
    if len(test_df) <

In [ ]:
if len(test_df) < len(test_df2):
    numdiff = len(test_df2) - len(test_df)
    newrows = test_df2[~test_df2.isin(test_df)]
    casenums = newrows['casenumber']


    txt = f"New update: {numdiff} new rows were added to the dataset."
    updtxt = f"New update: {numdiff} new heat death was recorded."

In [40]:
test_df2['casenumber'].equals(test_df['casenumber'])

False

In [54]:
newrows.columns

Index(['Unnamed: 0', 'casenumber', 'incident_date', 'death_date', 'age',
       'gender', 'race', 'latino', 'manner', 'primarycause',
       'primarycause_linea', 'secondarycause', 'gunrelated', 'opioids',
       'cold_related', 'heat_related', 'transportation_related',
       'commissioner_district', 'incident_street', 'incident_city',
       'incident_zip', 'longitude', 'latitude', 'location', 'residence_city',
       'residence_zip', 'objectid', 'chi_ward', 'chi_commarea',
       'covid_related', ':id', ':created_at', ':updated_at',
       'primarycause_lineb'],
      dtype='str')

In [67]:
test_df.columns

Index(['Unnamed: 0', 'casenumber', 'incident_date', 'death_date', 'age',
       'gender', 'race', 'latino', 'manner', 'primarycause',
       'primarycause_linea', 'secondarycause', 'gunrelated', 'opioids',
       'cold_related', 'heat_related', 'transportation_related',
       'commissioner_district', 'incident_street', 'incident_city',
       'incident_zip', 'longitude', 'latitude', 'location', 'residence_city',
       'residence_zip', 'objectid', 'chi_ward', 'chi_commarea',
       'covid_related', ':id', ':created_at', ':updated_at',
       'primarycause_lineb', 'inc_date', 'inc_time', 'dth_date', 'dth_time'],
      dtype='str')

In [73]:
test_df['inc_loc'] = test_df['incident_street'].str.upper() + ', ' + test_df['incident_city'] + ', IL'
test_df

,Unnamed: 0,casenumber,incident_date,death_date,age,gender,race,latino,manner,primarycause,...,covid_related,:id,:created_at,:updated_at,primarycause_lineb,inc_date,inc_time,dth_date,dth_time,inc_loc
0,0,ME2016-03171,2016-06-27T15:24:00.000,2016-06-27T16:36:00.000,83,Female,Black,False,NATURAL,HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...,...,False,row-cjgt_crd7-xyuy,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2016-06-27,15:24:00.000,2016-06-27,16:36:00.000,"9549 S PERRY AVE, CHICAGO, IL"
1,1,ME2017-04963,2017-10-22T04:56:00.000,2017-10-22T05:55:00.000,61,Male,Black,False,ACCIDENT,HYPERTHERMIA. EXPOSURE TO HIGH ENVIRONMENTAL T...,...,False,row-anqg-rrnp-nc7f,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,EXPOSURE TO HIGH ENVIRONMENTAL TEMPERATURE,2017-10-22,04:56:00.000,2017-10-22,05:55:00.000,"22600 CICERO AVENUE, RICHTON PARK, IL"
2,2,ME2017-04962,2017-10-22T08:50:00.000,2017-10-22T09:28:00.000,44,Male,Black,False,ACCIDENT,HYPERTHERMIA . EXPOSURE TO HIGH ENVIRONMENTAL ...,...,False,row-zkkj-326b.5nki,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,EXPOSURE TO HIGH ENVIRONMENTAL TEMPERATURE,2017-10-22,08:50:00.000,2017-10-22,09:28:00.000,"22660 S. CICERO AVE., RICHTON PARK, IL"
3,3,ME2019-02763,2019-06-17T15:00:00.000,2019-06-17T15:55:00.000,76,Male,Black,False,ACCIDENT,ENVIRONMENTAL HEAT EXPOSURE. FAULTY MODIFICATI...,...,False,row-bdwb~ncpq_653d,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,FAULTY MODIFICATION OF HOME FURNACE AND THERMO...,2019-06-17,15:00:00.000,2019-06-17,15:55:00.000,"18627 NIGHTINGALE TERRACE, COUNTRY CLUB HILLS, IL"
4,4,ME2015-03061,2015-07-19T01:00:00.000,2015-07-19T01:40:00.000,70,Female,White,False,NATURAL,HYPERTENSIVE CARDIOVASCULAR DISEASE,...,False,row-u2wg.si6s.22un,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2015-07-19,01:00:00.000,2015-07-19,01:40:00.000,"3614 MAPLE, BROOKFIELD, IL"
5,5,ME2018-03047,2018-06-30T09:33:00.000,2018-06-30T09:45:00.000,49,Male,White,False,NATURAL,HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...,...,False,row-4s8n~kc2j-xr4s,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2018-06-30,09:33:00.000,2018-06-30,09:45:00.000,"1610 WEST HADDON AVE, CHICAGO, IL"
6,6,ME2018-03654,2018-08-04T12:45:00.000,2018-08-04T13:23:00.000,81,Female,Black,False,NATURAL,HYPERTENSIVE CARDIOVASCULAR DISEASE,...,False,row-qnfn_9dzi.ryh2,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2018-08-04,12:45:00.000,2018-08-04,13:23:00.000,"2231 S. KOSTNER #1, CHICAGO, IL"
7,7,ME2016-03895,2016-08-10T11:26:00.000,2016-08-10T18:13:00.000,47,Female,White,True,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,...,False,row-89ey~272e.kmpt,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2016-08-10,11:26:00.000,2016-08-10,18:13:00.000,"11253 S ST. LAWRENCE AVE, CHICAGO, IL"
8,8,ME2015-03222,2015-07-28T19:37:00.000,2015-07-28T20:39:00.000,73,Female,White,False,NATURAL,ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE,...,False,row-cv5x_vpkg_t5y2,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2015-07-28,19:37:00.000,2015-07-28,20:39:00.000,"5026 SPRINGFIELD APT# 3E, CHICAGO, IL"
9,9,ME2015-01578,2015-04-17T19:45:00.000,2015-04-17T20:51:00.000,90,Female,Black,False,ACCIDENT,HYPERTENSIVE CARDIOVASCULAR DISEASE,...,False,row-69nx_tzpf~gwgh,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2015-04-17,19:45:00.000,2015-04-17,20:51:00.000,"9554 SOUTH WINSTON AVENUE, CHICAGO, IL"
10,10,ME2015-03060,2015-07-19T01:40:00.000,2015-07-19T02:02:00.000,69,Female,Black,False,NATURAL,HYPERTENSIVE CARDIOVASCULAR DISEASE,...,False,row-rpfe.upfy-6i43,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2015-07-19,01:40:00.000,2015-07-19,02:02:00.000,"4821 WEST CORTEZ, APT 1B, CHICAGO, IL"
11,11,ME2016-03517,2016-07-19T14:06:00.000,2016-07-19T14:46:00.000,63,Male,Black,False,NATURAL,HYPERTENSIVE AND ATHEROSCLEROTIC CARDIOVASCULA...,...,False,row-abf4~55am.fuim,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2016-07-19,14:06:00.000,2016-07-19,14:46:00.000,"1442 N. LONG AVENUE, CHICAGO, IL"
12,12,ME2018-02328,2018-05-16T17:25:00.000,2018-05-16T18:10:00.000,61,Female,Black,False,ACCIDENT,ENVIRONMENTAL HEAT EXPOSURE . MALFUNCTION OF A...,...,False,row-aabb~uneg-iqw7,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,MALFUNCTION OF A RESIDENTIAL THERMOSTAT,2018-05-16,17:25:00.000,2018-05-16,18:10:00.000,"3450 WEST 82ND PLACE, CHICAGO, IL"
13,13,ME2018-03034,2018-06-29T16:10:00.000,2018-06-29T16:20:00.000,36,Female,White,False,ACCIDENT,ETHANOL AND AMPHETAMINE TOXICITY,...,False,row-a6w7~azdj_7tzw,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2018-06-29,16:10:00.000,2018-06-29,16:20:00.000,"1850 NORTH CLARK STREET, CHICAGO, IL"
14,14,ME2019-03094,2019-07-05T10:30:00.000,2019-07-05T11:00:00.000,87,Female,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,...,False,row-2dcz.ifbk-2qam,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2019-07-05,10:30:00.000,2019-07-05,11:00:00.000,"2125 W. SHAKESPEARE AVENUE 2FL, CHICAGO, IL"
15,15,ME2019-03360,2019-07-20T14:49:00.000,2019-07-20T15:41:00.000,54,Male,White,False,NATURAL,CORONARY ATHEROSCLEROSIS,...,False,row-dr7b-ndbe~kyum,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2019-07-20,14:49:00.000,2019-07-20,15:41:00.000,"5233 N. LINCOLN AVENUE, CHICAGO, IL"
16,16,ME2019-03279,2019-05-05T11:30:00.000,2019-07-15T11:24:00.000,66,Male,White,False,ACCIDENT,HYPERTENSIVE AND ATHEROSCLEROTIC CARDIOVASCULA...,...,False,row-6efr-yfxa-pdtz,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2019-05-05,11:30:00.000,2019-07-15,11:24:00.000,"1060 WEST ADDISON, CHICAGO, IL"
17,17,ME2019-03366,2019-07-20T21:25:00.000,2019-07-20T21:50:00.000,71,Female,Black,False,NATURAL,HYPERTENSIVE-ARTERIOSCLEROTIC CARDIOVASCULAR D...,...,False,row-rbn4_2svs-xuwe,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2019-07-20,21:25:00.000,2019-07-20,21:50:00.000,"3326 WEST POLK, APT. 2, CHICAGO, IL"
18,18,ME2019-03372,2019-07-19T16:55:00.000,2019-07-21T06:23:00.000,56,Male,White,False,ACCIDENT,COMPLICATIONS OF HYPERTHERMIA. HEAT STROKE,...,False,row-38rh~sugb_i5qr,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,HEAT STROKE,2019-07-19,16:55:00.000,2019-07-21,06:23:00.000,"3617 W. PALMER STREET, CHICAGO, IL"
19,19,ME2019-05081,2019-10-28T11:02:00.000,2019-10-28T11:45:00.000,61,Female,Black,False,NATURAL,HYPERTENSIVE AND ATHEROSCLEROTIC CARDIOVASCULA...,...,False,row-e459.j7py_pccy,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2019-10-28,11:02:00.000,2019-10-28,11:45:00.000,"8230 S MARYLAND AVE, UNIT 1S, CHICAGO, IL"
20,20,ME2019-05731,2019-12-03T09:00:00.000,2019-12-03T09:49:00.000,79,Female,Black,False,ACCIDENT,ENVIRONMENTAL HEAT EXPOSURE. MALFUNCTION OF RE...,...,False,row-2ftk_xts3~5sgs,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,MALFUNCTION OF RESIDENTIAL HEATING SYSTEM,2019-12-03,09:00:00.000,2019-12-03,09:49:00.000,"3164 WEST 83RD PLACE, CHICAGO, IL"
21,21,ME2020-01244,2020-03-06T20:50:00.000,2020-03-06T21:33:00.000,55,Male,White,False,NATURAL,ATHEROSCLEROTIC CORONARY ARTERY DISEASE.,...,False,row-aqg3.ijzh.7jwp,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2020-03-06,20:50:00.000,2020-03-06,21:33:00.000,"3246 N. HALSTED STREET, CHICAGO, IL"
22,22,ME2020-08242,2020-06-25T14:51:00.000,2020-06-27T00:59:00.000,40,Male,White,True,ACCIDENT,COMPLICATIONS OF HYPERTHERMIA. COMBINATION OF ...,...,False,row-q6a4.pcf7.xazw,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,COMBINATION OF ENVIRONMENT AND FENTANYL AND CA...,2020-06-25,14:51:00.000,2020-06-27,00:59:00.000,"744 N. MONTICELLO AVENUE, CHICAGO, IL"
23,23,ME2020-08357,2020-06-27T20:56:00.000,2020-06-27T22:04:00.000,54,Female,White,False,ACCIDENT,HEAT STROKE,...,False,row-u5ws.w6f2.qc62,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2020-06-27,20:56:00.000,2020-06-27,22:04:00.000,4657 W. 95TH STREET (GATEWAY MOTEL PARKING LOT...
24,24,ME2020-08539,2020-07-01T16:57:00.000,2020-07-02T15:25:00.000,95,Female,Asian,False,ACCIDENT,HYPERTHERMIA. HEAT EXPOSURE,...,False,row-scpq.6bea-dukr,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,HEAT EXPOSURE,2020-07-01,16:57:00.000,2020-07-02,15:25:00.000,"6623 W BERRY AVE, CHICAGO, IL"
25,25,ME2020-08771,2020-07-09T12:30:00.000,2020-07-09T13:00:00.000,18,Female,White,True,ACCIDENT,HEAT STROKE,...,False,row-arry-74j3.gxt2,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2020-07-09,12:30:00.000,2020-07-09,13:00:00.000,"7643 W. BELMONT #2, ELMWOOD PARK, IL"
26,26,ME2020-11109,2020-10-04T14:10:00.000,2020-10-04T14:27:00.000,80,Male,Black,False,ACCIDENT,ENVIRONMENTAL HEAT EXPOSURE. FURNACE MALFUNCTI...,...,False,row-w66d-t2az_pjtj,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,FURNACE MALFUNCTIONING,2020-10-04,14:10:00.000,2020-10-04,14:27:00.000,"1212 SOUTH 15TH AVENUE, MAYWOOD, IL"
27,27,ME2020-11117,2020-10-04T14:10:00.000,2020-10-04T18:49:00.000,78,Female,Black,False,ACCIDENT,HYPERTHERMIA. FURNACE MALFUNCTIONING,...,False,row-zqq5.hk2v~z3xq,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,FURNACE MALFUNCTIONING,2020-10-04,14:10:00.000,2020-10-04,18:49:00.000,"1212 SOUTH 15TH AVENUE, MAYWOOD, IL"
28,28,ME2021-06815,2021-07-04T00:00:00.000,2021-07-17T06:34:00.000,65,Female,Black,False,ACCIDENT,COMPLICATIONS OF HEAT STROKE,...,False,row-b8ms~7syy~iujg,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2021-07-04,00:00:00.000,2021-07-17,06:34:00.000,"3500 S. KING DRIVE, CHICAGO, IL"
29,29,ME2021-07018,2021-07-24T17:16:00.000,2021-07-24T22:18:00.000,54,Male,White,False,ACCIDENT,FENTANYL AND PROBABLE COCAINE TOXICITY,...,False,row-gbc9~2a3j~yy5u,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2021-07-24,17:16:00.000,2021-07-24,22:18:00.000,"2140 W HADDON AVE, CHICAGO, IL"
30,30,ME2022-05305,2022-05-14T14:00:00.000,2022-05-14T14:39:00.000,76,Female,Black,False,ACCIDENT,ENVIRONMENTAL HEAT EXPOSURE. HOT RESIDENTIAL B...,...,False,row-mbkp-2h3w~2zy7,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,HOT RESIDENTIAL BUILDING DURING HEAT-RELATED W...,2022-05-14,14:00:00.000,2022-05-14,14:39:00.000,"7450 N ROGERS AVE APT 702, CHICAGO, IL"
31,31,ME2022-05310,2022-05-14T19:00:00.000,2022-05-14T19:04:00.000,72,Female,Black,False,ACCIDENT,ENVIRONMENTAL HEAT EXPOSURE. HOT RESIDENTIAL B...,...,False,row-h4xy_wi5x.iby5,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,HOT RESIDENTIAL BUILDING DURING HEAT-RELATED W...,2022-05-14,19:00:00.000,2022-05-14,19:04:00.000,"7450 N ROGERS AVE., APT. 904, CHICAGO, IL"
32,32,ME2022-05306,2022-05-14T11:10:00.000,2022-05-14T11:32:00.000,68,Female,Black,False,ACCIDENT,ENVIRONMENTAL HEAT EXPOSURE . HOT RESIDENTIAL ...,...,False,row-xj7q-kgue.dscz,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,HOT RESIDENTIAL BUILDING DURING A HEAT-RELATED...,2022-05-14,11:10:00.000,2022-05-14,11:32:00.000,"7450 NORTH ROGERS AVENUE, #405, CHICAGO, IL"
33,33,ME2022-05975,2022-06-14T18:33:00.000,2022-06-14T19:18:00.000,66,Female,Black,False,ACCIDENT,HYPERTHERMIA. ENVIRONMENTAL HEAT EXPOSURE,...,False,row-yxda_7uj4~5rhc,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,ENVIRONMENTAL HEAT EXPOSURE,2022-06-14,18:33:00.000,2022-06-14,19:18:00.000,"18TH AND STATE STREET, CHICAGO, IL"
34,34,ME2022-06215,2022-06-15T00:00:00.000,2022-06-25T21:16:00.000,77,Female,White,False,NATURAL,CORONARY ARTERY DISEASE,...,False,row-79cm_2ksd-b9p8,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2022-06-15,00:00:00.000,2022-06-25,21:16:00.000,NaN
35,35,ME2022-07256,2022-08-11T08:15:00.000,2022-08-11T08:30:00.000,31,Male,White,False,ACCIDENT,CHRONIC ETHANOLISM,...,False,row-ujup-mp7e-tbj4,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2022-08-11,08:15:00.000,2022-08-11,08:30:00.000,"3937 W ADDISON STREET, CHICAGO, IL"
36,36,ME2022-09517,2022-11-24T09:45:00.000,2022-11-24T09:55:00.000,58,Female,Black,False,ACCIDENT,ENVIRONMENTAL HEAT EXPOSURE. HOT APARTMENT UNI...,...,False,row-2km4_wjfk~u6m5,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,HOT APARTMENT UNIT IN RESIDENTIAL BUILDING,2022-11-24,09:45:00.000,2022-11-24,09:55:00.000,"6348 SOUTH ADA, UNIT 3, CHICAGO, IL"
37,37,ME2023-03049,2023-05-20T19:12:00.000,2023-05-20T10:41:00.000,60,Female,White,False,ACCIDENT,HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...,...,False,row-rvat_dsh4_48ia,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2023-05-20,19:12:00.000,2023-05-20,10:41:00.000,"6330 S STONY ISLAND, CHICAGO, IL"
38,38,ME2023-03958,2023-06-30T15:05:00.000,2023-06-30T13:38:00.000,53,Male,White,False,NATURAL,ATHEROSCLEROTIC CARDIOVASCULAR DISEASE,...,False,row-fy3a_8yc9~xm8f,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2023-06-30,15:05:00.000,2023-06-30,13:38:00.000,"1062 COPPERFIELD LANE, SCHAUMBURG, IL"
39,39,ME2023-04799,2023-08-11T11:15:00.000,2023-08-11T10:54:00.000,33,Male,Black,False,ACCIDENT,"COMBINED DRUG (COCAINE, FENTANYL, AND 4-ANPP (...",...,False,row-fuen.gn2q.thep,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2023-08-11,11:15:00.000,2023-08-11,10:54:00.000,"1420 W. MARQUETTE RD, CHICAGO, IL"
40,40,ME2024-02421,2024-04-30T12:18:00.000,2024-04-30T11:30:00.000,68,Male,Black,False,ACCIDENT,COMPLICATIONS OF HEAT STROKE,...,False,row-vsbi.8xr4.v98v,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2024-04-30,12:18:00.000,2024-04-30,11:30:00.000,"5400 W 87TH ST, BURBANK, IL"
41,41,ME2024-03289,2024-06-18T12:23:00.000,2024-06-18T10:29:00.000,83,Female,Black,False,NATURAL,HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...,...,False,row-kktx~vqbs_jehn,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2024-06-18,12:23:00.000,2024-06-18,10:29:00.000,"8531 S. BISHOP ST BASEMENT APT, CHICAGO, IL"
42,42,ME2024-04024,2024-07-23T16:33:00.000,2024-07-23T16:22:00.000,62,Male,Black,False,ACCIDENT,FENTANYL AND DIPHENHYDRAMINE TOXICITY,...,False,row-qad3~nzzr-qcup,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2024-07-23,16:33:00.000,2024-07-23,16:22:00.000,"3800 CICERO AVE., CICERO, IL"
43,43,ME2024-04714,2024-08-27T00:43:00.000,2024-08-28T00:27:00.000,35,Male,Black,False,NATURAL,HYPERTROPHIC CARDIOMYOPATHY,...,False,row-3tdg-vit8.j6e2,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2024-08-27,00:43:00.000,2024-08-28,00:27:00.000,"7 S MAYFIELD AVENUE#107, CHICAGO, IL"
44,44,ME2024-07003,2024-12-21T15:26:00.000,2024-12-21T13:35:00.000,60,Female,White,False,ACCIDENT,ENVIRONMENTAL HEAT EXPOSURE . PROLONGED CONTAC...,...,False,row-uy6e.kxrx_uv5v,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,PROLONGED CONTACT WITH HOT SHOWER WATER,2024-12-21,15:26:00.000,2024-12-21,13:35:00.000,"19 TIMBER LANE, NORTHBROOK, IL"
45,45,ME2025-02669,2025-05-15T19:55:00.000,2025-05-15T17:46:00.000,80,Female,Am. Indian,False,ACCIDENT,HEAT STROKE,...,False,row-qgn6-88u2-djxv,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2025-05-15,19:55:00.000,2025-05-15,17:46:00.000,"7615 ROOSEVELT RD, FOREST PARK, IL"
46,46,ME2025-03384,2025-06-24T18:50:00.000,2025-06-24T16:25:00.000,40,Male,White,True,ACCIDENT,ACUTE ETHANOL TOXICITY,...,False,row-9tkf_2seb~gppz,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2025-06-24,18:50:00.000,2025-06-24,16:25:00.000,"3135 W. 53RD ST., CHICAGO, IL"
47,47,ME2025-03437,2025-06-26T15:30:00.000,2025-06-26T14:37:00.000,82,Male,White,False,NATURAL,HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...,...,False,row-vgr8~txzr.i4h8,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2025-06-26,15:30:00.000,2025-06-26,14:37:00.000,"6901 W. HIGGINS UNIT 3W, CHICAGO, IL"
48,48,ME2025-03680,2025-07-07T18:53:00.000,2025-07-07T18:02:00.000,70,Male,White,True,NATURAL,MYOCARDIAL INFARCTION. HYPERTENSIVE-ARTERIOSCL...,...,False,row-tqk4-dc8y.z2g6,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,HYPERTENSIVE-ARTERIOSCLEROTIC-VALVULAR HEART D...,2025-07-07,18:53:00.000,2025-07-07,18:02:00.000,"1000 W O'HARE AVE, CHICAGO, IL"
49,49,ME2026-03456,2026-07-01T13:09:00.000,2026-07-01T12:32:00.000,69,Male,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,...,False,row-qr98-f75u.wfvp,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,NaN,2026-07-01,13:09:00.000,2026-07-01,12:32:00.000,"1210 DARROW APT 2, EVANSTON, IL"
50,50,ME2026-03475,2026-07-01T23:33:00.000,2026-07-01T20:31:00.000,46,Male,White,False,ACCIDENT,HYPERTHERMIA. ENVIRONMENTAL HEAT EXPOSURE IN T...,...,False,row-rzej~pb48-7b4c,2026-08-01T20:53:17.197Z,2026-08-01T20:53:17.197Z,ENVIRONMENTAL HEAT EXPOSURE IN THE SETTING OF ...,2026-07-01,23:33:00.000,2026-07-01,20:31:00.000,"W 63RD STREET & S CAMPBELL AVENUE, CHICAGO, IL"

In [82]:
import tabulate

In [137]:
test_df2 = test_df

In [139]:
# if the new scrape DOES NOT EQUAL the last scrape...

if test_df2.equals(test_df) != 'True': # in this case, it'll be the newest scrape against the penultimate scrape
    # get the row difference
    numdiff = len(test_df2) - len(test_df) 

    # drop nonmatching rows (and yes, there's probably a better way to do this)
    newrows = test_df2[~test_df2.isin(test_df)] 
    newrows = newrows[~newrows['casenumber'].isna()]

    # generating things for text
    caselist = newrows['casenumber']
    
    # data table
    # data cleaning that could literally be done anywhere else but for some reason i'm doing it here ugh
    newrows['age'] = newrows['age'].astype('str')
    newrows['age'] = newrows['age'].str.replace('.0','',regex=True)

    newrows['latino'] = newrows['latino'].astype('str')
    newrows['latino'] = newrows['latino'].str.replace('False','',regex=True)
    newrows['latino'] = newrows['latino'].str.replace('True','Latino',regex=True)

    newrows['incident_zip'] = newrows['incident_zip'].astype('str')
    newrows['incident_zip'] = newrows['incident_zip'].str.replace('.0','',regex=False)


    newrows['inc_loc'] = newrows['incident_street'].str.upper() + ', ' + newrows['incident_city'] + ', IL ' + newrows['incident_zip']
    newrows['inc_loc'] = newrows['inc_loc'].str.title()


    newrows['maploc'] = newrows['inc_loc'].str.replace(' ','+',regex=True)
    gmaps_start = "https://google.com/maps/place/"
    newrows['gmaps_link'] = "<" + gmaps_start + newrows['maploc'] + "/ | here >"

    # newrows['gmaps_link'] = f'<{gmaps_start}/{maploc}/ | >'

    # concatenate to get a big string
    newrows_trunc = newrows[['casenumber','inc_date','dth_date','age', 'incident_city', 'gender','race','latino','primarycause','secondarycause','inc_loc','chi_ward','chi_commarea','residence_city','gmaps_link']]
    
    # make it a string list
    newrows_trunc['stringy'] = "• *Case number " + newrows_trunc['casenumber'] + "* — a " + newrows_trunc['age'] + "-year-old " + newrows_trunc['latino'] + " " + newrows_trunc['race'] + " " + newrows_trunc['gender'].str.lower() + " in " + newrows_trunc['incident_city'].str.title() + ". \n The determined cause of death is " + newrows_trunc['primarycause'] + " and " + newrows_trunc['secondarycause'] + ". The death date was *" + newrows_trunc['dth_date'] + "* and the incident that led to their death was on *" + newrows_trunc['inc_date'] + "* at " + newrows_trunc['inc_loc'] + ". 📍 view incident location " + newrows_trunc['gmaps_link'] + ". \n"
    stringy_list = newrows_trunc['stringy']

    ########
    # send leading message about the update with the diff#

    text = textgenerator(test_df, test_df2)
    formatted = f'❗️ *{placeholder} update — {rightnow}* \n {text} \n'
    send_message(formatted, SLACK_WEBHOOK)

    # send the details about each row in the diff #
    # for every new row in the new data, send a message with that row's contents
    for item in list(stringy_list):

        # dataformat = f'The updated data rows are below: \n {list}'
        send_message(item, SLACK_WEBHOOK)

In [109]:
print(newdata)

|    | casenumber   | inc_date   | dth_date   | gender   | race   | latino   | primarycause                                            | secondarycause                                                                                  | inc_loc                                        |   chi_ward | chi_commarea       | residence_city   |
|---:|:-------------|:-----------|:-----------|:---------|:-------|:---------|:--------------------------------------------------------|:------------------------------------------------------------------------------------------------|:-----------------------------------------------|-----------:|:-------------------|:-----------------|
| 51 | ME2026-03491 | 2026-07-02 | 2026-07-02 | Male     | Black  |          | HEAT STROKE                                             | ETHANOL INTOXICATION                                                                            | 2916 W. POLK AVE, CHICAGO, IL 612              |         28 | EAST GARFIELD PARK | Chicago          |
| 52 | ME2026-03506 | 2026-07-03 | 2026-07-03 | Male     | White  | Latino   | HYPERTENSIVE AND ATHEROSCLEROTIC CARDIOVASCULAR DISEASE | DIABETES MELLITUS; HEAT STRESS                                                                  | 3288 S ARCHER AVE UNIT 2, CHICAGO, IL 8        |         12 | MCKINLEY PARK      | Chicago          |
| 53 | ME2026-03513 | 2026-07-03 | 2026-07-03 | Female   | Black  |          | HYPERTENSIVE CARDIOVASCULAR DISEASE                     | ASTHMA, OBESITY, HEAT STRESS                                                                    | 1016 W 70TH ST APT 1E, CHICAGO, IL 621         |         16 | ENGLEWOOD          | Chicago          |
| 54 | ME2026-03523 | 2026-07-02 | 2026-07-04 | Male     | White  | Latino   | HEAT STROKE                                             | HYPERTENSION, DIABETES MELLITUS, OBESITY                                                        | 6318 S. MOZART, CHICAGO, IL 629                |         15 | CHICAGO LAWN       | Chicago          |
| 55 | ME2026-03638 | 2026-06-29 | 2026-07-09 | Female   | White  | Latino   | COMPLICATIONS OF HEAT STROKE                            | SCHIZOPHRENIA                                                                                   | W 53RD AND S HALSTEAD, CHICAGO, IL 9           |         20 | NEW CITY           | Chicago          |
| 56 | ME2026-03649 | 2026-06-29 | 2026-07-10 | Male     | White  |          | COMPLICATIONS OF FALL(S)                                | DYSPHAGIA, CHRONIC ETHANOLISM, PAROXYSMAL ATRIAL FLUTTER/TACHYCARDIA, OSTEOPOROSIS, HEAT STRESS | 1944 GARDNER ROAD, WESTCHESTER, IL 154         |        nan | nan                | Westchester      |
| 57 | ME2026-03743 | 2026-07-14 | 2026-07-14 | Male     | White  |          | ORGANIC CARDIOVASCULAR DISEASE                          | HEAT STRESS DUE TO ENVIRONMENTAL HYPERTHERMIA                                                   | 9001 S CICERO AVE TRAILER 92, OAK LAWN, IL 453 |        nan | nan                | Oak Lawn         |

In [ ]:
$